// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vigilo.Storage;

#nullable disable

namespace Vigilo.Storage.Migrations
{
    [DbContext(typeof(VigiloDbContext))]
    [Migration("20260908104704_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Vigilo.Core.EmailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DigestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FoldersToMonitor")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImapHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImapPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollingFallbackMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentFoldersToMonitor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StoreMessageBodies")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseImapIdle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Vigilo.Core.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageIdHeader")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalHtmlBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTextBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("References")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageIdHeader");

                    b.HasIndex("ThreadKey");

                    b.HasIndex("AccountId", "ProviderMessageId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Folder", "ReceivedAt");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("Vigilo.Core.LiveReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommercialOfferCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueTodayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscalationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastMessageProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NeedsReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessedMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpcomingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaitingReplyCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LiveReports");
                });

            modelBuilder.Entity("Vigilo.Core.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackedItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedItemId", "Kind", "DedupeKey")
                        .IsUnique();

                    b.ToTable("NotificationRecords");
                });

            modelBuilder.Entity("Vigilo.Core.OutlookCategorySyncOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredCategoriesJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessageSanitized")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VigiloMessageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("VigiloMessageId", "Status");

                    b.ToTable("OutlookCategorySyncOperations");
                });

            modelBuilder.Entity("Vigilo.Core.OutlookItemBinding", b =>
                {
                    b.Property<Guid>("VigiloMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownFolderEntryId")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastMatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutlookEntryId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlookStoreId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("VigiloMessageId");

                    b.ToTable("OutlookItemBindings");
                });

            modelBuilder.Entity("Vigilo.Core.OutlookStoreBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutlookStoreDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlookStoreId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VigiloMailboxId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VigiloMailboxId")
                        .IsUnique();

                    b.ToTable("OutlookStoreBindings");
                });

            modelBuilder.Entity("Vigilo.Core.ProcessedEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassificationAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassifierModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmailMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagsHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("ImapUid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastClassificationFailureKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastClassificationRecoveryKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageIdHeader")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextClassificationAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UidValidity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId");

                    b.HasIndex("MessageIdHeader");

                    b.HasIndex("ProcessingStatus", "NextClassificationAttemptAt");

                    b.HasIndex("AccountId", "Folder", "LastSeenAt");

                    b.HasIndex("AccountId", "Folder", "UidValidity", "ImapUid")
                        .IsUnique();

                    b.ToTable("ProcessedEmails");
                });

            modelBuilder.Entity("Vigilo.Core.SenderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedSenderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "NormalizedSenderEmail")
                        .IsUnique();

                    b.ToTable("SenderRules");
                });

            modelBuilder.Entity("Vigilo.Core.TrackedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionSummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEscalation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresReply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionOverride")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentReplyDetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentReplyMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.HasIndex("MessageType", "Status");

                    b.HasIndex("Status", "Deadline");

                    b.HasIndex("ThreadKey", "Status");

                    b.ToTable("TrackedItems");
                });

            modelBuilder.Entity("Vigilo.Core.EmailMessage", b =>
                {
                    b.HasOne("Vigilo.Core.EmailAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.NotificationRecord", b =>
                {
                    b.HasOne("Vigilo.Core.TrackedItem", null)
                        .WithMany()
                        .HasForeignKey("TrackedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.OutlookCategorySyncOperation", b =>
                {
                    b.HasOne("Vigilo.Core.EmailMessage", null)
                        .WithMany()
                        .HasForeignKey("VigiloMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.OutlookItemBinding", b =>
                {
                    b.HasOne("Vigilo.Core.EmailMessage", null)
                        .WithOne()
                        .HasForeignKey("Vigilo.Core.OutlookItemBinding", "VigiloMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.OutlookStoreBinding", b =>
                {
                    b.HasOne("Vigilo.Core.EmailAccount", null)
                        .WithOne()
                        .HasForeignKey("Vigilo.Core.OutlookStoreBinding", "VigiloMailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.ProcessedEmail", b =>
                {
                    b.HasOne("Vigilo.Core.EmailAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vigilo.Core.EmailMessage", null)
                        .WithMany()
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vigilo.Core.SenderRule", b =>
                {
                    b.HasOne("Vigilo.Core.EmailAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vigilo.Core.TrackedItem", b =>
                {
                    b.HasOne("Vigilo.Core.EmailMessage", null)
                        .WithOne()
                        .HasForeignKey("Vigilo.Core.TrackedItem", "EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
